# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80fd6b0ac52ea06d217d8fef63d8e4bc18927e4b99c67a47443e9a79e4ade691bd239c6049d143304be0fc852659819edf02c866f87783872f7b89d923bfa3e7

test:
  secret_key_base: 223c1ab85251e77e52ab4bec848e2bf2dd09c28af3cfec76df25e0f1e8a3a56e9936f07cef1fed9fa7cb70c3f02c1f9d69eea8534d1b146fdadab8cb0567b3fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
